theme: jekyll-theme-minimal
logo: /assets/img/profile.jpg
title: Ayaka (Murata) Naganuma
description: ""
github_username:  ayaka-qc
# url: "https://hiroki11x.github.io/"
url: "linkedin.com/in/ayaka-naganuma-065879117"

github:
  is_project_page: false

include:
  - _pages
